version: '3.8'
services:
  web:
    build: .
    command: bash -c "python django-react/manage.py makemigrations && python django-react/manage.py migrate && python django-react/manage.py runserver 0.0.0.0:8000"
    container_name: wsb_app
    volumes:
      - .:/app
    ports:
      - 8000:8000

